### ISSUE TITLE
breaks  growth moment screen

### ISSUE THREAD

**Issue by weresd282** [Lakuna/RimWorld-Well-Met#16] opened 2022-11-06 15:42 UTC
### Description

growth moment screen is bugged out when a child grows up and soft locks games

### Version

1.4

### Environment details

just harmony and Well met loaded

### Steps to reproduce

have a child grow up

**Comment by Lakuna** [comment] 2022-11-06 15:45
Duplicate of #15.

**Closed by Lakuna** 2022-11-06 15:45 UTC
Labels: bug
