### ISSUE TITLE
Well met hides the traits to get when child growth occurs

### ISSUE THREAD

**Issue by FlorestNerd19** [Lakuna/RimWorld-Well-Met#17] opened 2022-11-15 15:19 UTC
### Description

when the time to chose my pawns kids traits, it frezes the windown and shows no traits.
 log revealled that it is because this mod changes the traits values to null
`Exception filling window for RimWorld.Dialog_GrowthMomentChoices: System.ArgumentNullException: Value cannot be null.`

### Version

v1.4

### Environment details

just this mod cause this error.

### Possible solution

removing the mod cleared the error and allowed me to chose

**Comment by Lakuna** [comment] 2022-11-15 18:53
Closing as duplicate of #15.

**Closed by Lakuna** 2022-11-15 18:53 UTC
Labels: bug
